### ISSUE TITLE
Have an option to buy/short current price with a limit order

### ISSUE THREAD

**Issue by ohmygawd** [jrhurley2/TDInterface-Public#28]
For example:

I want to buy 100 shares of spy and the current price is 100 dollars. Have a button that takes the current price and makes it a limit order of a 100 dollars per a share so I don't get any slippage.

**Comment by jrhurley2** [comment]
So I assume your are talking about  a the trigger with the OCO order that I currently have.    So if the Limit was blank and I were to just assume either Last or Bid or Ask, would that be suficient.   What would you prefer  Last or Bid/Ask depending on direction?

**Comment by ohmygawd** [comment]
Actually, what I would like to see is a feature that Steve uses is market limit. Buy limit with 5 (customizable) cents offset above the market/ask for long or bid for short.

Example:

Market Price 100

I'm willing to buy up to 100.05 so a market buy + 5 cent offset.

I hope this makes sense.
