### ISSUE TITLE
Area where you can input the next resistance price (vwap, DL, higher low, etc) 

### ISSUE THREAD

**Issue by ohmygawd** [jrhurley2/TDInterface-Public#33]
Input where you can enter the next resistance price long/short (vwap, DL, higher low, etc) and the app will tell you if you have enough room to get a 1 to 1. If this area is blank or left unanswered you can tell make a trade.

**Comment by jrhurley2** [comment]
Can you please elaborate, what would I base the calculations off of.  Last, BId/ask, Limit?

**Comment by ohmygawd** [comment]
Last would be great. In the future, maybe a setting to let the user pick from last, bid/ask

**Comment by ohmygawd** [comment]
I thought about it some more. I don't want to enter the next resistance price. I want the app to calculate what the first R is so I can see it in my chart and quickly make a decision if it's worth the risk

Something like below:
Enter Stop: $1
Enter Limit Buy: $1.5

App calculates first r is at $2.0

**Comment by ohmygawd** [comment]
Thanks for adding to where 1 R will be

**Comment by ohmygawd** [comment]
Closing
