### ISSUE TITLE
Adding trigger price and GTX (X days) without using buying power until price be triggered

### ISSUE THREAD

**Issue by PX0420** [jrhurley2/TDInterface-Public#57]
Hi Jrhurley2

Could you please add trigger price and good until X days (Incl pre-market and after hours) function, so we can store ready-to-trigger orders on our own pc to buy more shares when price be triggered, far more than the using buying power to split on those stocks.
Another reason is TD doesn't support buy stop limit for extended hour as well.

So please help.

Thank you so much

**Comment by brandoncorry** [comment]
We wouldn't be able to save the orders on the client, as there is no guarantee we can catch and get the order filled. You can set up these orders in TD, but you cannot have stops in after hours (except on futures), so there is not a way to solve this that I'm aware of.
