### ISSUE TITLE
Flatten Position

### ISSUE THREAD

**Issue by brandoncorry** [jrhurley2/TDInterface-Public#75]
Need an easy way to flatten a position - if you open a position and have a OCO, you can't just click the 100% market button - as it throws an error with the existing OCO in place.

Would need to either update the specific 100% button(s) to cancel any orders and send order to close all - or crate a 'flatten' button similar to Active Trader in ToS.

**Comment by brandoncorry** [comment]
@jrhurley2 I think this was fixed with your latest update as part of the TradeStation integration?

**Comment by jrhurley2** [comment]
Yes.  If you hit 100% it should flatten.  Only in tda

Sent via the Samsung Galaxy S21 Ultra 5G, an AT&T 5G smartphone
Get Outlook for Android<https://aka.ms/AAb9ysg>
________________________________

**Comment by brandoncorry** [comment]
This should be resolved with the updates to cancel OCO when exit buttons are clicked. Closing as this was part of the tradestation integration.
