### ISSUE TITLE
Exit trade buttons stop working after cancelling a take profit order before it is hit

### ISSUE THREAD

**Issue by brandoncorry** [jrhurley2/TDInterface-Public#86]
Was in a trade, had an order for my STOP only, no take profits. Clicking the market exit buttons did nothing. I didn't see anything in the logs, so may need to add some additional logging with some timestamps, as the log is difficult to read with all the quotes and orders.

Might break out the logs to help reduce what is in specific ones - Orders.log, Quotes.log, etc.

1. Create a regular trade with stop and take profit OCO orders (i.e. Disable 1st Target Profit is not set, so it creates two orders)
2. Try to take any market % of your position off (it won't work - sometimes I realize it was a bad entry, and want out)
3. Cancel the take profit order (to keep your stop in place while you do this) - I do this in ToS
4. Try to exit any % with the market exit % buttons - i.e. 100%
5. Nothing happens
![FailedExitAfterTakeProfitCancelled](https://user-images.githubusercontent.com/17894275/221052450-558c221d-7be5-4169-840c-ee6b52760a71.png)

**Comment by jrhurley2** [comment]
Updated to check to see if stop is part of OCO order,  If it is, cancel all orders and take profit
