### ISSUE TITLE
Occasional negative value in 1:1 box

### ISSUE THREAD

**Issue by jhholbro** [jrhurley2/TDInterface-Public#99]
Broker: TradeStation
TDInterface Version: 3.1.3

1:1 box periodically displays a negative value.  May be related to "Error getting postion for SPY" seen in log file

https://user-images.githubusercontent.com/44213221/222245984-bc94d362-d723-4917-928b-9cac411b7e4f.mp4
[20230301-143158.log](https://github.com/jrhurley2/TDInterface-Public/files/10864660/20230301-143158.log)

**Comment by brandoncorry** [comment]
Thanks for reporting. We believe we have a fix for this, which we will release shortly - marking as duplicate of #72.

**Comment by jhholbro** [comment]
@brandoncorry, I'm testing 3.1.6 this morning and it looks like your fix worked for the long side, but I'm still seeing the issue for short positions.

**Comment by brandoncorry** [comment]
> @brandoncorry, I'm testing 3.1.6 this morning and it looks like your fix worked for the long side, but I'm still seeing the issue for short positions.

@jhholbro - interesting - I'm not able to repro

Are you using TD Ameritrade or TradeStation?

**Comment by jhholbro** [comment]
@brandoncorry,  I’m using TradeStation

**Comment by brandoncorry** [comment]
We believe this was fixed as pat of all the work we did around cleaning this up. We haven't seen it on TDA or TS trading... please let us know if you are still seeing it @jhholbro
